application: meetupgator
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /
  static_files: index.html
  upload: index.html

- url: /proxy
  script: proxy.py